version: '3.3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    hostname: mysql-develop
    environment:
      MYSQL_DATABASE: 'timekeeping_database'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'toanelnino'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'toanelnino@1902'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'toanelnino@1902'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '23306:3306'
    expose:
      # Opens port 3306 on the container
      - '23306'
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql

  redis:
    image: "redis:alpine"
    hostname: velo-redis-develop
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "26379:6379"

